'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DLTool_Form
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EI_DLTool.DLTool_Form", GetType(DLTool_Form).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Center.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_BackgroundImageLayout() As System.Windows.Forms.ImageLayout
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.BackgroundImageLayout", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageLayout)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Popup.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=491,Y=290}.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=35}.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 5.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compile.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Text() As String
            Get
                Return ResourceManager.GetString("Compile_Button.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to False.
        '''</summary>
        Friend Shared ReadOnly Property Compile_Button_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile_Button.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property DestDir_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("DestDir.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=44}.
        '''</summary>
        Friend Shared ReadOnly Property DestDir_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DestDir.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property DestDir_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("DestDir.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=643, Height=26}.
        '''</summary>
        Friend Shared ReadOnly Property DestDir_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DestDir.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 2.
        '''</summary>
        Friend Shared ReadOnly Property DestDir_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DestDir.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\.
        '''</summary>
        Friend Shared ReadOnly Property DestDir_Text() As String
            Get
                Return ResourceManager.GetString("DestDir.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Popup.
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("DirSearch.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=663,Y=44}.
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("DirSearch.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("DirSearch.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=26}.
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("DirSearch.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 7.
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("DirSearch.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ....
        '''</summary>
        Friend Shared ReadOnly Property DirSearch_Text() As String
            Get
                Return ResourceManager.GetString("DirSearch.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Center.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_BackgroundImageLayout() As System.Windows.Forms.ImageLayout
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.BackgroundImageLayout", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageLayout)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Popup.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=596,Y=290}.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=35}.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 4.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_Button.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download.
        '''</summary>
        Friend Shared ReadOnly Property Download_Button_Text() As String
            Get
                Return ResourceManager.GetString("Download_Button.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to Center.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_BackgroundImageLayout() As System.Windows.Forms.ImageLayout
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.BackgroundImageLayout", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageLayout)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Popup.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_FlatStyle() As System.Windows.Forms.FlatStyle
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.FlatStyle", resourceCulture)
                Return CType(obj,System.Windows.Forms.FlatStyle)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_ImeMode() As System.Windows.Forms.ImeMode
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.ImeMode", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImeMode)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=20,Y=290}.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=35}.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 11.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Text() As String
            Get
                Return ResourceManager.GetString("EditConfigButton.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to False.
        '''</summary>
        Friend Shared ReadOnly Property EditConfigButton_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("EditConfigButton.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=180,Y=17}.
        '''</summary>
        Friend Shared ReadOnly Property FBD_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("FBD.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 25.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_ItemHeight() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.ItemHeight", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to XPR300.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Items() As String
            Get
                Return ResourceManager.GetString("HypModelList.Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HPR400XD.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Items1() As String
            Get
                Return ResourceManager.GetString("HypModelList.Items1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=104,Y=197}.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=117, Height=54}.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 1.
        '''</summary>
        Friend Shared ReadOnly Property HypModelList_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("HypModelList.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Label1_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property Label1_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=16,Y=12}.
        '''</summary>
        Friend Shared ReadOnly Property Label1_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property Label1_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=176, Height=20}.
        '''</summary>
        Friend Shared ReadOnly Property Label1_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 3.
        '''</summary>
        Friend Shared ReadOnly Property Label1_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Label1.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package Save Location.
        '''</summary>
        Friend Shared ReadOnly Property Label1_Text() As String
            Get
                Return ResourceManager.GetString("Label1.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Label2_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property Label2_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=176}.
        '''</summary>
        Friend Shared ReadOnly Property Label2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=2,Top=0,Right=2,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property Label2_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=20}.
        '''</summary>
        Friend Shared ReadOnly Property Label2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 9.
        '''</summary>
        Friend Shared ReadOnly Property Label2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Label2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Machine.
        '''</summary>
        Friend Shared ReadOnly Property Label2_Text() As String
            Get
                Return ResourceManager.GetString("Label2.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property Label3_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property Label3_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=101,Y=176}.
        '''</summary>
        Friend Shared ReadOnly Property Label3_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=2,Top=0,Right=2,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property Label3_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=104, Height=20}.
        '''</summary>
        Friend Shared ReadOnly Property Label3_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 10.
        '''</summary>
        Friend Shared ReadOnly Property Label3_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("Label3.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration.
        '''</summary>
        Friend Shared ReadOnly Property Label3_Text() As String
            Get
                Return ResourceManager.GetString("Label3.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Rubik, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=87}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=13, Height=19}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 6.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Text() As String
            Get
                Return ResourceManager.GetString("NotificationLabel.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to False.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLabel_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLabel.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to True.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_AutoSize() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.AutoSize", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Rubik, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=130}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=0,Right=4,Bottom=0}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=13, Height=19}.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 8.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ..
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Text() As String
            Get
                Return ResourceManager.GetString("NotificationLable2.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Boolean similar to False.
        '''</summary>
        Friend Shared ReadOnly Property NotificationLable2_Visible() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("NotificationLable2.Visible", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=15, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Font() As System.Drawing.Font
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.Font", resourceCulture)
                Return CType(obj,System.Drawing.Font)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 25.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_ItemHeight() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.ItemHeight", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SP600.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Items() As String
            Get
                Return ResourceManager.GetString("SPMachineList.Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SP700.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Items1() As String
            Get
                Return ResourceManager.GetString("SPMachineList.Items1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SP900.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Items2() As String
            Get
                Return ResourceManager.GetString("SPMachineList.Items2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Point similar to {X=20,Y=197}.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Location() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.Location", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=4,Top=4,Right=4,Bottom=4}.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Margin() As System.Windows.Forms.Padding
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.Margin", resourceCulture)
                Return CType(obj,System.Windows.Forms.Padding)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Size similar to {Width=77, Height=79}.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_Size() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.Size", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Int32 similar to 0.
        '''</summary>
        Friend Shared ReadOnly Property SPMachineList_TabIndex() As Integer
            Get
                Dim obj As Object = ResourceManager.GetObject("SPMachineList.TabIndex", resourceCulture)
                Return CType(obj,Integer)
            End Get
        End Property
    End Class
End Namespace
